name: calificator
description: Calificator App.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  http: ^0.13.4
  stomp_dart_client: ^0.4.4
  horizontal_picker: ^1.2.0
  loading_animation_widget:
  circular_chart_flutter: ^0.0.2
  fl_chart: ^0.62.0
  time_machine: ^0.9.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/my_config.json
    - flutter_assets/bcs_classifier_preProcDE-channels.tflite
    - flutter_assets/bcslabel.txt
    - flutter_assets/detect.tflite
    - flutter_assets/kite.jpg
    - flutter_assets/labelmap.txt
    - flutter_assets/transfer.txt
