activemq:
  username: admin
  password: admin
  brokerUrl: tcp://localhost:61616
  receive-timeout: 10000

images:
  queue:
    name: IMAGE_QUEUE

spring:
  flyway:
    enabled: true
    schemas: ${spring.datasource.schema}
    locations: classpath:/db/scripts/migration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/server
    schema: server

  jpa:
    database-platform=org:
      hibernate:
        dialect:
          MySQL5InnoDBDialect: com.mysql.jdbc.Driver
flyway:
  user: root
  password: root
  schemas: server