server:
  port: 8080
activemq:
  username: admin
  password: admin
  brokerUrl: tcp://localhost:61616
  receive-timeout: 10000

images:
  queue:
    name: IMAGE_QUEUE
  path: /tmp/images

spring:
  flyway:
    enabled: true
    schemas: ${spring.datasource.schema}
    locations: classpath:/db/scripts/migration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/server
    schema: server


flyway:
  user: root
  password: root
  schemas: server