CREATE TABLE server.`SESSION`(
	ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	START_DATE DATETIME NOT NULL,
	END_DATE DATETIME NOT NULL
);

CREATE TABLE server.`SET`(
    ID VARCHAR(36)  NOT NULL PRIMARY KEY COMMENT 'Identificación (uuid) que agrupa las imágenes realizadas a una caravana',
    `POSITION` SMALLINT NOT NULL COMMENT 'Posición del animal en la caravana',
   CREATED_DATE DATETIME NOT NULL
);


CREATE TABLE server.IMAGE(
    ID BIGINT(20) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SET_ID VARCHAR(36) NOT NULL COMMENT 'Identificación (uuid) que agrupa las imágenes realizadas a una caravana',
    SESSION_ID BIGINT(20) NOT NULL,
    `PATH` VARCHAR(100) NOT NULL UNIQUE COMMENT 'Directorio + nombre del archivo',
     CONSTRAINT  `fk_IMAGE_SESSION_ID` FOREIGN KEY (`SESSION_ID`) REFERENCES `SESSION` (`ID`),
     CONSTRAINT  `fk_IMAGE_SET_ID` FOREIGN KEY (`SET_ID`) REFERENCES `SET` (`ID`)
);

CREATE TABLE server.CARAVAN(
	ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    IDENTIFICATOR VARCHAR(100) NULL COMMENT  'Identificador definido por el calificador'
);

CREATE TABLE server.CARAVAN_IMAGE(
	IMAGE_ID VARCHAR(100),
    CARAVAN_ID BIGINT(20),
	PRIMARY KEY(IMAGE_ID,CARAVAN_ID),
	CONSTRAINT  `fk_CARAVAN_IMAGE_CARAVAN_ID` FOREIGN KEY (`CARAVAN_ID`) REFERENCES `CARAVAN` (`ID`)
);



CREATE TABLE server.PREDICTED_SCORE(
    SET_ID VARCHAR(36) NOT NULL PRIMARY KEY ,
    SCORE DECIMAL(5, 4) NOT NULL COMMENT 'Puntaje definido por el algoritmo de predicción',
    CONSTRAINT `fk_PREDICTED_SCORE_SET_ID` FOREIGN KEY (`SET_ID`) REFERENCES `SET` (`ID`)
) COMMENT 'Puntaje para una caravana en una sesión dada definido por el algoritmo de predicción';




CREATE TABLE server.CALIFICATOR(
	ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
	USER_NAME VARCHAR(36) NOT NULL
);

CREATE TABLE server.CALIFICATED_SCORE(
    ID BIGINT(20) AUTO_INCREMENT PRIMARY KEY,
    SESSION_ID BIGINT(20) NOT NULL,
    SET_ID VARCHAR(36) NOT NULL,
    CALIFICATOR_ID  BIGINT(20) NOT NULL,
    SCORE DECIMAL(5, 4) NOT NULL COMMENT 'Puntaje definido por el calificador',
    CONSTRAINT `fk_CALIFICATED_SCORE_SET_ID` FOREIGN KEY (`SET_ID`) REFERENCES `SET` (`ID`),
    CONSTRAINT  `fk_CALIFICATED_SCORE_SESSION_ID` FOREIGN KEY (`SESSION_ID`) REFERENCES `SESSION` (`ID`),
    CONSTRAINT  `fk_CALIFICATED_SCORE_CALIFICATOR_ID` FOREIGN KEY (`CALIFICATOR_ID`) REFERENCES `CALIFICATOR` (`ID`)

) COMMENT 'Puntaje para una caravana en una sesión dada definido por uno o mas calificadores';
