version: '3.8'

services:
  activemq:
    image: quay.io/artemiscloud/activemq-artemis-broker
    container_name: activemq
    ports:
      - "61616:61616"
    environment:
      AMQ_USER: admin
      AMQ_PASSWORD: admin

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci

volumes:
  mysql_data:
