name: mercadosalud
description: Paciente de Mercado Salud.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

#to see old packages
#flutter pub outdated

#problemas de build...
#flutter clean

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  image_picker: ^0.7.3

  mercadosaludlib:
    path: ../ 

  flutter:
    sdk: flutter
  
  simple_gesture_detector: ^0.2.0
    # Firebase
  firebase_core: ^1.1.0
  firebase_auth: ^1.1.2
  google_sign_in: ^5.0.4
  sign_in_with_apple: ^3.0.0
  # Stacked State Management
  stacked: ^2.1.1
  stacked_services: ^0.8.5
  stacked_firebase_auth: ^0.2.5

  auth_buttons: ^1.0.1
  easy_localization: ^3.0.0
#custom loaders
  easy_localization_loader:
    git: https://github.com/aissat/easy_localization_loader.git
  flutter_hooks:
  cloud_firestore:  ^2.2.0
  firebase_storage: ^8.0.5
  firebase_messaging: ^10.0.0
  cached_network_image: ^3.0.0
# data models
  flamingo: ^2.4.1
  flamingo_annotation:
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  logger: ^1.0.0
  animations: ^2.0.0
  flutter_form_builder: ^6.0.1
  phone_number: ^0.11.0
  connectivity_plus: ^1.0.4
  mailer: ^5.0.0
  cloud_functions: ^1.1.2
  mustache_template: ^2.0.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  #maps and geolocation dependencies
  location: ^4.1.1
  google_maps_flutter: ^2.0.5
  geoflutterfire:
  geocoding: ^2.0.0
  country_pickers: ^2.0.0
  form_builder_image_picker: ^1.0.0-nullsafety.0
  flutter_email_sender: ^5.0.1
  url_launcher: ^6.0.9

dev_dependencies:
#flutter pub run change_app_package_name:main com.new.package.name
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  build_runner:
  flamingo_generator: ^0.11.0
  stacked_generator: ^0.4.1
  # data models
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
  # Testing
  mockito: 
  #  test: ^1.14.4
  cloud_firestore_mocks:
  firebase_storage_mocks:
  flutter_launcher_icons: ^0.9.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/ms.icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: false 

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - resources/langs/
    - assets/images/ms.splash.png
    - assets/images/ms.splash2.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
#flutter_intl:
#  enabled: true